edu:
  image: 'carre/educational-aggregator:0.2'
  command: ['npm', 'start']
  environment:
    - LANGUAGE=el
    - API_URL=https://devices.carre-project.eu/ws/
    - TOKEN_NAME=CARRE_USER
    - RDF_TOKEN=xxxxxxxxxxxxxxxxxxxx
    - AUTH_URL=https://devices.carre-project.eu/devices/accounts/
    - GRAPH_URL=carre.kmi.open.ac.uk
  restart: always
  ports:
    - '3001:80'

entry:
  image: 'carre/risk-entry-system:0.2'
  command: ['/bin/bash', './env']
  environment:
    - LANGUAGE=el
    - API_URL=https://carre.kmi.open.ac.uk/ws/
    - CACHE_URL=https://cache.duth.carre-project.eu/
    - AUTH_URL=https://devices.carre-project.eu/devices/accounts/
    - GRAPH_URL=carre.kmi.open.ac.uk
  restart: always  
  ports:
    - '3002:80'

cache:
  image: 'carre/cache-server:0.2'
  restart: always  
  ports:
    - '3003:80'
